<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\web.Common\web.Common.csproj" />
    <ProjectReference Include="..\web.HttpClients\web.HttpClients.csproj" />
    <ProjectReference Include="..\web.Interface.Repository\web.Interface.Repository.csproj" />
    <ProjectReference Include="..\web.Interface.Service\web.Interface.Service.csproj" />
    <ProjectReference Include="..\web.Models\web.Models.csproj" />
    <ProjectReference Include="..\web.Repository\web.Repository.csproj" />
    <ProjectReference Include="..\web.Service\web.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="E:\Work_Space\01_Web_Code\MVC_Core_Solution\WebCode\WebCode\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="E:\Work_Space\01_Web_Code\MVC_Core_Solution\WebCode\WebCode\.editorconfig" />
  </ItemGroup>

</Project>
